LoudubProject/urls.py
from django.contrib import admin
from django.urls import path, include
from LoudubSite import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('LoudubSite.urls')),

]

LoudubSite/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import sign_up, CustomLoginView, logout_view, contact_us, admin_mail_view, delete_message, update_message
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', contact_us, name='contact'),
    path('about/', views.about, name='about'),
    path('register/', sign_up, name='sign_up'),
    path('login/', CustomLoginView.as_view(), name='log_in'),
    path('logout/', logout_view, name='log_out'),
    path('profile/', views.profile, name='profile'),
    path('profile/mail/', admin_mail_view, name='admin_mail'),
    path('delete-message/<int:id>/', delete_message, name='delete_message'),
    path('update-message/<int:id>/', update_message, name='update_message'),

]

LoudubSite/models.py
# models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if not extra_fields.get('is_staff'):
            raise ValueError("Superuser must have is_staff=True.")
        if not extra_fields.get('is_superuser'):
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']


class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.subject} - {self.email}"

LoudubSite/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from .models import CustomUser, ContactMessage

class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match!")
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already registered!")
        return email


class LoginForm(AuthenticationForm):
    username = forms.EmailField(label="Email", widget=forms.EmailInput)

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']

LoudubSite/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.sites import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.contrib.auth import login,logout
from django.contrib.auth.views import LoginView
from .forms import SignUpForm, LoginForm, ContactMessage, ContactForm
import json

def home(request):
    return render(request, 'index.html')

def contact(request):
    return render(request, 'contact.html')

def about(request):
    return render(request, 'generic.html')

def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user)
            return redirect('profile')
    else:
        form = SignUpForm()
    return render(request, 'sign_up.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'login.html'
    authentication_form = LoginForm

def logout_view(request):
    logout(request)
    return redirect('home')

@login_required
def profile(request):
    messages = ContactMessage.objects.all().order_by('-created_at') if request.user.is_staff else None
    return render(request, 'profile.html', {'messages': messages})
def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact.html',{'form': ContactForm(), 'success': True})
    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

@login_required
def admin_mail_view(request):
    if not request.user.is_staff:
        return render(request, 'login.html' )
    messages = ContactMessage.objects.all().order_by('-created_at')
    return render(request, 'mail_content.html', {'messages': messages})


def delete_message(request, id):
    if request.method == 'DELETE':
        message = get_object_or_404(ContactMessage, id=id)
        message.delete()
        return JsonResponse({'success': True})

def update_message(request, id):
    if request.method == 'PUT':
        try:
            data = json.loads(request.body)
            message = get_object_or_404(ContactMessage, id=id)

            if 'message' in data:
                message.message = data['message']
                message.save()

            return JsonResponse({'status': 'success', 'message': 'Message updated successfully'})
        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Invalid JSON data'})

LoudubSite/templates/contact.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>loudub</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../static/css/main.css" />
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1><a href="{% url 'home' %}" >Loudub</a> </h1>
					<nav id="nav">
						<ul>
							<li><a href="index.html">Home</a></li>
							<li>
								<a href="#" class="icon solid fa-angle-down">More</a>
								<ul>
									<li><a href="{% url 'about' %}">About</a></li>
                                </ul>
							</li>
                            {% if user.is_authenticated %}
                                <li><a href = "{% url 'profile' %}" class = 'button'>Profile</a></li>
                            {% else %}
							    <li><a href="{% url 'sign_up' %}" class = "button">Sign Up</a></li>
                            {% endif %}
						</ul>
					</nav>
				</header>

<section id="main" class="container medium">
    <header>
        <h2>Contact Us</h2>
        <p>Tell us what you think about our little operation.</p>
    </header>
    <div class="box">
        <form method="post">
            {% csrf_token %}

            {% if success %}
                <p class="success-message">Your message has been sent successfully!</p>
            {% endif %}

            <div class="row gtr-50 gtr-uniform">
                <div class="col-6 col-12-mobilep">
                    <label for="id_name">Name</label>
                    {{ form.name }}
                </div>
                <div class="col-6 col-12-mobilep">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                </div>
                <div class="col-12">
                    <label for="id_subject">Subject</label>
                    {{ form.subject }}
                </div>
                <div class="col-12">
                    <label for="id_message">Message</label>
                    {{ form.message }}
                </div>
                <div class="col-12">
                    <ul class="actions special">
                        <li><input type="submit" value="Send Message" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon brands fa-twitter"><span class="label">X</span></a></li>
						<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="../static/js/jquery.min.js"></script>
			<script src="../static/js/jquery.dropotron.min.js"></script>
			<script src="../static/js/jquery.scrollex.min.js"></script>
			<script src="../static/js/browser.min.js"></script>
			<script src="../static/js/breakpoints.min.js"></script>
			<script src="../static/js/util.js"></script>
			<script src="../static/js/main.js"></script>

	</body>
</html>

LoudubSite/templates/generic.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Loudub</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../static/css/main.css" />
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1><a href="{% url 'home' %}">Loudub</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="{% url 'home' %}">Home</a></li>
							<li>
								<a href="#" class="icon solid fa-angle-down">More</a>
								<ul>
									<li><a href="{% url 'contact' %}">Contact</a></li>
								</ul>
							</li>
							<li><a href="#" class="button">Sign Up</a></li>
						</ul>
					</nav>
				</header>

			<!-- Main -->
				<section id="main" class="container">
					<header>
						<h2>History</h2>
						<p>“if you want to shine like sun first you have to burn like it.”</p>
					</header>
					<div class="box">
						<span class="image featured"><img src="../static/images/loudub.jpg" alt="" /></span>
						<h2>The Story of LOUDUB</h2>
                        <p>
                            In the rapidly evolving digital world, content knows no boundaries. However, language has always been
                            a barrier that limits creators from reaching their full potential. This challenge inspired the birth of
                            <strong>LOUDUB</strong>, a project founded with a bold vision: to break down language barriers and give every
                            creator a truly global voice.
                        </p>
                        <p>
                            It all started when <strong>Vladislav</strong>, the visionary founder of LOUDUB, realized the growing demand for
                            multilingual content among YouTube creators. With a passion for innovation and a deep understanding of the power
                            of communication, he set out to develop a platform that could revolutionize the way content is shared across the world.
                        </p>
                        <p>
                            At first, the journey wasn't easy. Translating and dubbing videos with accuracy, while preserving the original voice
                            and emotions, seemed like an impossible task. But with persistence and a dedicated team, LOUDUB harnessed the power of
                            <strong>AI-driven voice synthesis</strong> and advanced <strong>translation technologies</strong> to create something
                            groundbreaking—an automated solution that delivers <strong>natural, high-quality multilingual dubbing</strong> while
                            retaining the original tone and style of the creator.
                        </p>
                        <p>
                            The first breakthrough came when LOUDUB partnered with small content creators, helping them expand their reach beyond
                            their native audience. As word spread about the seamless, AI-powered dubbing process, larger influencers and businesses
                            soon took notice. LOUDUB grew from a small startup into a <strong>leading player in the content localization industry</strong>,
                            trusted by creators from all over the world.
                        </p>
                        <h3>Our Services</h3>
                        <ul>
                            <li>Automatic video translation into multiple languages.</li>
                            <li>Voice cloning technology, preserving the creator’s unique tone and style.</li>
                            <li>Seamless integration with YouTube and other platforms, making content localization effortless.</li>
                            <li>Affordable and scalable solutions, ensuring accessibility for everyone—from independent creators to large media companies.</li>
                        </ul>
                        <p>
                            What sets LOUDUB apart is not just its cutting-edge technology, but its commitment to
                            <strong>helping creators grow</strong> without losing their authenticity. Every video dubbed through LOUDUB
                            carries the original emotion and intent, allowing audiences to connect with the content on a deeper level.
                        </p>
                        <p>
                            As LOUDUB continues to evolve, the mission remains the same: <strong>to empower creators by making their content
                            accessible to the world, one language at a time.</strong>
                        </p>
                        <p><strong>Join us on this journey and make your voice heard across the globe with LOUDUB.</strong></p>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon brands fa-twitter-square"><span class="label">X</span></a></li>
						<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="../static/js/jquery.min.js"></script>
			<script src="../static/js/jquery.dropotron.min.js"></script>
			<script src="../static/js/jquery.scrollex.min.js"></script>
			<script src="../static/js/browser.min.js"></script>
			<script src="../static/js/breakpoints.min.js"></script>
			<script src="../static/js/util.js"></script>
			<script src="../static/js/main.js"></script>

	</body>
</html>

LoudubSite/templates/index.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Loudub</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../static/css/main.css" />
	</head>
	<body class="landing is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header" class="alt">
					<h1><a href="{% url 'home' %}">Loudub</a></h1>
					<nav id="nav">
						<ul>
							<li><a href="{% url 'home' %}">Home</a></li>
							<li>
								<a href="#" class="icon solid fa-angle-down">More</a>
								<ul>
									<li><a href="{% url 'about' %}">About</a></li>
									<li><a href="{% url 'contact' %}">Contact</a></li>
								</ul>
							</li>
                            {% if user.is_authenticated %}
                                <li><a href = "{% url 'profile' %}" class = 'button'>Profile</a></li>
                            {% else %}
							    <li><a href="{% url 'sign_up' %}" class = "button">Sign Up</a></li>
                            {% endif %}
						</ul>
					</nav>
				</header>

			<!-- Banner -->
				<section id="banner">
					<h2>Loudub</h2>
					<p>Speaking your world, your words.</p>
					<ul class="actions special">
						<li><a href="{% url 'log_in' %}" class="button primary">Try</a></li>
						<li><a href="{% url 'sign_up' %}" class="button">Sign Up</a></li>
					</ul>
				</section>

			<!-- Main -->
				<section id="main" class="container">

					<section class="box special">
						<header class="major">
							<h2>LOUDUB: Global Voices, One Platform
								<br /> Seamless Dubbing, Limitless Reach</h2>
							<p>LOUDUB simplifies video dubbing with multilingual voice integration, helping you reach global audiences effortlessly..</p>
						</header>
						<span class="image featured"><img src="../static/images/pic01.jpg" alt="" /></span>
					</section>
					<section class="box special features">
						<div class="features-row">
							<section style="flex: 1; text-align: center; padding: 20px;">
								<h3>About LOUDUB</h3>
                                <p><b>LOUDUB</b> is an innovative platform for dubbing video content into multiple languages using advanced speech synthesis technology. We help YouTube creators and other content producers reach a wider audience by providing high-quality translations and voiceovers in their own voice.</p>
							</section>
							<section style="flex: 1; text-align: center; padding: 20px;">
								<h3> Our Services </h3>
                                <ul>
                                    <li>Automatic video translation into 30+ languages.</li>
                                    <li>Voiceovers using AI to match the original creator's voice.</li>
                                    <li>Ready-to-use solutions for YouTube, social media, and educational platforms.</li>
                                    <li>Personalized approach and high-quality audio production.</li>
                                </ul>
							</section>
							<section style="flex: 1; text-align: center; padding: 20px;">
								<h3>Why Choose Us</h3>
								<p>Our team is committed to delivering top-tier dubbing services by adapting content for different markets and audiences. With a powerful API and user-friendly interface, LOUDUB is the choice for professionals looking to expand their reach without extra costs.</p>
							</section>
						</div>
					</section>

					<div class="row">
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src="../static/images/pic02.jpg" alt="" /></span>
								<h3>Be in touch</h3>
								<p>Explore the journey behind LOUDUB and discover how we revolutionize content localization with innovative AI-powered dubbing solutions.</p>
								<ul class="actions special">
									<li><a href="{% url 'about' %}" class="button alt">Learn More</a></li>
								</ul>
							</section>

						</div>
						<div class="col-6 col-12-narrower">

							<section class="box special">
								<span class="image featured"><img src="../static/images/pic03.jpg" alt="" /></span>
								<h3>Soon</h3>
								<p>Stay tuned! Soon, you'll find detailed information and links to explore everything about our project and its exciting features..</p>
								<ul class="actions special">
									<li><a href="#" class="button alt">Learn More</a></li>
								</ul>
							</section>

						</div>
					</div>

				</section>

			<!-- CTA -->
				<section id="cta">

					<h2>Sign up for beta access</h2>
					<p>Fill your personal informaition below, and get your chance to get beta access to our product!</p>

					<form>
						<div class="row gtr-50 gtr-uniform">
							<div class="col-8 col-12-mobilep">
								<input type="email" name="email" id="email" placeholder="Email Address" />
							</div>
							<div class="col-4 col-12-mobilep">
								<input type="submit" value="Send" class="fit" />
							</div>
						</div>
					</form>

				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">
						<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="../static/js/jquery.min.js"></script>
			<script src="../static/js/jquery.dropotron.min.js"></script>
			<script src="../static/js/jquery.scrollex.min.js"></script>
			<script src="../static/js/browser.min.js"></script>
			<script src="../static/js/breakpoints.min.js"></script>
			<script src="../static/js/util.js"></script>
			<script src="../static/js/main.js"></script>

	</body>
</html>

LoudubSite/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <title>Log In</title>
    <style>
        body {
            background-color: #f8f9fa;
        }
        .login-container {
            background: hsla(230, 71%, 56%, 1);
            background: linear-gradient(180deg, hsla(230, 71%, 56%, 1) 0%, hsla(221, 44%, 41%, 1) 88%);
            color: white;
            padding: 30px;
            border-radius: 8px;
            max-width: 500px;
            margin: 50px auto;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }
        .btn-custom {
            height: 50px;
            width: 200px;
            position: relative;
            background-color: transparent;
            cursor: pointer;
            border: 2px solid #f77f77;
            overflow: hidden;
            border-radius: 30px;
            color: #f77f77;
            transition: all 0.5s ease-in-out;
            z-index: 1;
            font-weight: 800;
            letter-spacing: 4px;
            margin-top: 20px;
        }
        .btn-custom:hover {
            box-shadow: 1px 1px 200px #f77f77;
            color: #fff;
            border: none;
        }

        .text-center{
            color: white;
        }

        label {
            color: white;
        }
        
        .form-group {
            text-decoration-color: #2b2b2b;
        }
        input[type="text"], 
        input[type="email"], 
        input[type="password"] {
        color: #000; 
        background-color: #fff; }

        input[type="text"]:focus, 
        input[type="email"]:focus, 
        input[type="password"]:focus {
        color: #000; /* Чорний текст */
        background-color: #f8f9fa; /* Світло-сірий фон */
        border: 2px solid #007bff; /* Синя рамка під час фокусу */
    
    }
    </style>
</head>
<body>
    <div class="login-container">
        <h2 class="text-center">Log In</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email Address</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                {{ form.password }}
            </div>
            <button type="submit" class="btn btn-custom btn-block">Log In</button>
        </form>
        <p class="text-center mt-3">
            Don't have an account? <a href="{% url 'sign_up' %}" class="text-light">Sign Up</a>
        </p>
    </div>
</body>
</html>

LoudubSite/templates/mail_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <section id="main" class="container medium">
        <header>
            <h2>Messages</h2>
            <p>Here are the messages sent through the contact form.</p>
        </header>
        <div class="box">
            <ul>
                {% for message in messages %}
                    <li>
                        <strong>{{ message.name }}</strong> ({{ message.email }})<br>
                        <em>{{ message.subject }}</em><br>
                        {{ message.message }}<br>
                        <small>Sent at: {{ message.created_at }}</small>
                    </li>
                {% empty %}
                    <p>No messages yet.</p>
                {% endfor %}
            </ul>
        </div>
    <h2>Messages</h2>
    <ul>
        {% for message in messages %}
        <li>
            {{ message.name }} - {{ message.subject }}
            <a href="{% url 'update_message' message.id %}">Edit</a>
            <a href="{% url 'delete_message' message.id %}">Delete</a>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'create_message' %}">Create New Message</a>
    </section>

</body>
</html>

LoudubSite/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="../static/css/profile.css">
</head>
<body>
    <div class="sidebar" id="sidebar">
        <div class="toggle-btn" onclick="toggleSidebar()">☰</div>

        <div class="menu-item" onclick="showContent('subscription')">
            <i class="fas fa-book"></i>
            <span class="menu-text">Subscription</span>
        </div>

        {% if user.is_staff %}
        <div class="menu-item" onclick="showContent('mail')">
            <i class="fas fa-envelope"></i>
            <span class="menu-text">Mail</span>
        </div>
        {% endif %}

        {% if user.is_staff %}
        <a href="{% url 'admin:index' %}" class ='menu-link'>
            <div class="menu-item" onclick="showContent('admin')">
                <i class="fas fa-user-secret"></i>
                <span class="menu-text">Admin</span>
            </div>
        </a>
        {% endif %}

        <div class="menu-item" onclick="showContent('work_surface')">
            <i class="fas fa-briefcase"></i>
            <span class="menu-text">Work Surface</span>
        </div>

        <div class="logout" onclick="logout()">
            <i class="fas fa-sign-out-alt"></i>
            <span class="menu-text">Log out</span>
        </div>
    </div>

    <div class="main-content">
        <div class="content" id="content">

            <div id="subscription-content" style="display: none;">
                <div class="subscriptions-container">
                    <div class="subscription-card">
                        <h3>Basic Plan</h3>
                        <p>Price: $9.99/month</p>
                        <ul>
                            <li>Access to basic features</li>
                            <li>Email support</li>
                            <li>200 minutes of video dubbing</li>
                        </ul>
                        <button class="pay-button" href="#">Subscribe</button>
                    </div>

                    <div class="subscription-card">
                        <h3>Standard Plan</h3>
                        <p>Price: $19.99/month</p>
                        <ul>
                            <li>Everything in Basic Plan</li>
                            <li>Priority email support</li>
                            <li>500 minutes of video dubbing</li>
                        </ul>
                        <button class="pay-button" href="#">Subscribe</button>
                    </div>

                    <div class="subscription-card">
                        <h3>Premium Plan</h3>
                        <p>Price: $29.99/month</p>
                        <ul>
                            <li>Everything in Standard Plan</li>
                            <li>24/7 telegram-chat support</li>
                            <li>Up to 1500 minutes of video dubbing</li>
                        </ul>
                        <button class="pay-button" href="#">Subscribe</button>
                    </div>
                </div>


            </div>

            <div id="mail-content" style="display: none;">
                <h2>Contact Messages</h2>
                <ul>
                    {% for message in messages %}
                        <li class="message-item", id="message--{{ messages.id }}">
                            <strong>{{ message.name }}</strong> ({{ message.email }})<br>
                             <textarea id="message-text-{{ message.id }}">{{ message.message }}</textarea><br>
                            <small>Sent at: {{ message.created_at }}</small>
                            <br>

                            <button class ="update-button" onclick="updateMessage({{ message.id }})">Update</button>

                            <button class="delete-button" onclick="deleteMessage({{ message.id }})">Delete</button>
                        </li>
                    {% empty %}
                        <p>No messages yet.</p>
                    {% endfor %}
                </ul>
            </div>

           <div id="work_surface-content" style="display: none;">
               <h2>Text-to-Speech Generator</h2>
               <h3>SOON...</h3>
               
           </div>



    </div>
</div>

    <script>const logoutUrl = "{% url 'log_out' %}";</script>
    <script src="../static/js/profile.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js" defer></script>
</body>
</html>